<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_equipos  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["AfterDelete"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		
    // Obtener el ID del equipo recién insertado
    $idequipo = $keys["id"];  // Asegúrate de que el campo ID esté correctamente referenciado
    
    // Obtener todos los idevaluador de la tabla 'evaluador'
    $sql_evaluador = "SELECT idevaluador FROM evaluador";
    $rs_evaluadores = CustomQuery($sql_evaluador);
    
    // Recorrer los evaluadores obtenidos
    while ($data_evaluador = db_fetch_array($rs_evaluadores)) {
        $idevaluador = $data_evaluador["idevaluador"];
        
        // Insertar en la tabla 'criterio' con los valores obtenidos
        $insert_sql = "INSERT INTO criterio (idevaluador, idequipo) VALUES ($idevaluador, $idequipo)";
        CustomQuery($insert_sql);
    }
    
    // Obtener el último ID de la tabla 'preguntas'
    $sql_pregunta = "SELECT MAX(id) as id_pregunta FROM preguntas";  // Campo 'id' de la tabla 'preguntas'
    $rs_pregunta = CustomQuery($sql_pregunta);
    $data_pregunta = db_fetch_array($rs_pregunta);
    $id_pregunta = $data_pregunta["id_pregunta"];

    // Actualizar la tabla 'criterio' con el id_pregunta obtenido
    $update_sql = "UPDATE criterio SET id_preguntas = $id_pregunta WHERE idequipo = $idequipo";
    CustomQuery($update_sql);


;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, $pageObject)
{

		
    // Obtener el ID del equipo eliminado
    $idequipo = $deleted_values["id"];  // Asegúrate de que el campo ID esté correctamente referenciado

    // Eliminar registros relacionados en la tabla 'criterio'
    $delete_criterio_sql = "DELETE FROM criterio WHERE idequipo = $idequipo";
    CustomQuery($delete_criterio_sql);

    // Eliminar registros relacionados en la tabla 'integrantes'
    $delete_integrantes_sql = "DELETE FROM integrantes WHERE idequipo = $idequipo";
    CustomQuery($delete_integrantes_sql);
    
    // Mensaje opcional de confirmación
    $message = "Los registros relacionados han sido eliminados correctamente.";


;		
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
